/uav/camera/down/down_usb_cam:
  ros__parameters:
    video_device: "/dev/v4l/by-path/pci-0000:00:15.0-usb-0:1.3:1.0-video-index0"
      # ls -al /dev/v4l/by-path/
      # v4l2-ctl --list-devices
    framerate: 25.0
    image_width: 640
    image_height: 480
    pixel_format: "mjpeg2rgb"
    camera_frame_id: "down_camera"
    camera_name: "down_camera"