/uav/camera/front/front_usb_cam:
  ros__parameters:
    video_device: "/dev/v4l/by-id/usb-Jieli_Technology_USB_Composite_Device-video-index0"
      # Stable camera path by USB device ID.
      # Check:
      #   ls -al /dev/v4l/by-id/
      #   v4l2-ctl --list-devices
      #   v4l2-ctl -d /dev/v4l/by-id/usb-Jieli_Technology_USB_Composite_Device-video-index0 --list-formats-ext
    framerate: 25.0
    image_width: 640
    image_height: 480
    pixel_format: "mjpeg2rgb"
    frame_id: "front_camera"
    camera_name: "front_camera"
