std_msgs/Header header

bool has_target
uint32 track_id
float32 priority_score

float32 center_x_norm
float32 center_y_norm
float32 bbox_area_norm
string distance_bucket

float32 error_x_norm
float32 error_y_norm
string horizontal_command
string vertical_command
string range_command
string motion_command

float32 recommended_body_forward_m
float32 recommended_body_right_m
bool centered
bool ready_to_inspect
string reason
